---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spark-batch
  namespace: crypto-pipeline
spec:
  schedule: "*/2 * * * *"  # Chạy mỗi 2 phút cho demo Realtime
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: spark-batch
            image: gcr.io/crypto-project-bigdata/spark-jobs:v2
            imagePullPolicy: Always
            # Dùng spark-submit có trong path của image này (đã set ENV SPARK_HOME)
            command: ["/opt/spark/bin/spark-submit"]
            args:
              - --master
              - local[2]
              - /app/simple_analytics.py

            
            env:
            - name: SPARK_HOME
              value: "/opt/spark"
            - name: HDFS_DATA_DIR
              value: "/app/data"
            - name: PYTHONUNBUFFERED
              value: "1"
            
            volumeMounts:
            - name: hdfs-data
              mountPath: /app/data
            
            resources:
              requests:
                memory: "2Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
          
          volumes:
          - name: hdfs-data
            persistentVolumeClaim:
              claimName: hdfs-data-pvc
